### ISSUE TITLE
MDN Cutover EFS/RDS Transfer Dry-Run

### ISSUE THREAD

**Issue by escattone** [mdn/infra#127]
Before executing the MDN cut-over plan, we'd like to do a dry-run of the RDS (DB) and EFS (file attachments and legacy files) content transfers, so we are ready for the actual cut-over on the morning of Oct. 29th and so we have an accurate idea how long the transfer operations will take.

# Acceptance Criteria
* [x] EFS content transferred from MozMEAO to MozIT (in the MDN Cutover Plan, document the commands required if they aren't already)
* [x] Time estimate for the EFS content transfer when we do the actual cutover
* [x] RDS content transferred from MozMEAO to MozIT (in the MDN Cutover Plan, document the commands required if they aren't already)
* [x] Time estimate for the RDS content transfer when we do the actual cutover
* [x] Document any follow-on tasks as new issues

**Comment by escattone** [comment]
@limed and I completed this today. Here are the results:
- @limed has a daily `migration-sync` CronJob running in the `mdn-prod` namespace of the MozIT `oregon` cluster that takes care of syncing the EFS backups from MozMEAO to MozIT, so the time required for this on the day of the cutover will be minimal, only a few minutes for one final sync just to be safe
- @limed's `migration-sync` CronJob also takes care of syncing the daily (@metadave switched them to daily on Tuesday Oct. 16) RDS backups from the S3 bucket in MozMEAO to the one in MozIT
- the RDS transfer test we ran today, which included copying the RDS backup from the MozIT S3 bucket onto the admin node and then piping it through a decryption and decompression pipeline into the MozIT production MySQL instance, required about 45 minutes to complete
- the complete set of steps including commands and time required was documented, and a redacted copy was inserted into the [MDN Cutover Plan](https://docs.google.com/document/d/1Dre3dNbfw-PJ77sdPfnCIKnRO0gv_nEJi51shMiadeQ/edit?usp=sharing)
- no follow-on tasks are required

**Comment by limed** [comment]
I'm going to consider this one done as well :)
