### ISSUE TITLE
Upgrade RDS from 5.6 to 5.7

### ISSUE THREAD

**Issue by limed** [mdn/infra#170]
Upgrade the RDS instance from version `5.6.35` (the current production version) to version `5.7` to take advantage of the `max_execution_time` setting. This is considered a major upgrade so we should really test this in stage before moving forward.

Valid upgrade targets from version `5.6.35` are `5.7.16`, `5.7.17`, `5.7.19`, `5.7.21`, `5.7.22` and `5.7.23`

**Comment by jwhitlock** [comment]
I'd also like ``innodb_large_prefix`` setting, to get us closer to (shudder) [emoji support on MDN](https://bugzilla.mozilla.org/show_bug.cgi?id=857438#c11).

**Comment by jwhitlock** [comment]
I think the first step is running MySQL 5.7 in the development environment, in a branch or master, to see if there are any issues identified by our Django tests. We'd need to get that into our sprint planning, starting in sprint 2 (Feb 11) at the earliest, if developers are doing the dev environment work.

**Comment by jwhitlock** [comment]
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1525165 for Kuma changes. There's a blocking Kuma change to enable strict mode (https://github.com/mdn/sprints/issues/917) that blocks the development upgrade and infra tasks.

**Comment by escattone** [comment]
I don't think this is necessary any longer with the launch of Yari.
