### ISSUE TITLE
Enable RDS performance insight

### ISSUE THREAD

**Issue by limed** [mdn/infra#172]
Enable this https://aws.amazon.com/blogs/database/tuning-amazon-rds-for-mysql-with-performance-insights/

Start with stage first then move on to prod

**Comment by limed** [comment]
Doing a little more research on this it seems that this will only work with MySQL version `5.6.41` or higher.  Current version of the RDS database is `5.6.35` and the upgrade path to `5.6.41` is considered a minor version upgrade

> Amazon RDS MySQL version 5.7.22 and higher 5.7 versions
Amazon RDS MySQL version 5.6.41 and higher 5.6 versions

Based on https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.html

**Comment by jwhitlock** [comment]
We're using MySQL 5.6.42 in development. We use the latest 5.6 docker image, and get minor updates automatically. There appear to be no code changes needed for a 5.6.41 or later update.

I assume the site will be unavailable during a database update. Read-only mode still requires a working database, but the CDN would help us a bit by caching content for at most 5 minutes. I think the fully available version looks like this:

1) Announce a maintenance window on MDN, preferably during off-peak hours (US nights or weekends).
2) At the start of the window, re-deploy the site in read-only maintenance mode. Wait about 2 minutes for writes to finish.
3) Create a clone of the database, and update the clone to latest MySQL 5.6.x
4) Re-deploy web, celery, etc. deployments with a new ``DATABASE_URL`` pointing to the new server,
5) Re-deploy again, but in normal read-write mode (alternatively, do this at the same time as the ``DATABASE_URL`` update.

If we're comfortable with some downtime, we can do the same maintenance window announcement, and let AWS perform a live update of the DB. This would take less effort, and maybe AWS claims this can be a no-downtime update. 

I'd support the full no-downtime version, as a safe way to test our process before a riskier 5.7 update.

**Comment by limed** [comment]
> We're using MySQL 5.6.42 in development. We use the latest 5.6 docker image, and get minor updates automatically. There appear to be no code changes needed for a 5.6.41 or later update.
> 
> I assume the site will be unavailable during a database update. Read-only mode still requires a working database, but the CDN would help us a bit by caching content for at most 5 minutes. I think the fully available version looks like this:
> 
>     1. Announce a maintenance window on MDN, preferably during off-peak hours (US nights or weekends).
> 
>     2. At the start of the window, re-deploy the site in read-only maintenance mode. Wait about 2 minutes for writes to finish.
> 
>     3. Create a clone of the database, and update the clone to latest MySQL 5.6.x
> 
>     4. Re-deploy web, celery, etc. deployments with a new `DATABASE_URL` pointing to the new server,
> 
>     5. Re-deploy again, but in normal read-write mode (alternatively, do this at the same time as the `DATABASE_URL` update.
> 
> 
> If we're comfortable with some downtime, we can do the same maintenance window announcement, and let AWS perform a live update of the DB. This would take less effort, and maybe AWS claims this can be a no-downtime update.
> 
> I'd support the full no-downtime version, as a safe way to test our process before a riskier 5.7 update.

This sounds good to me, I think that there will be some downtime for a minor upgrade but yes testing this process will be a good test for the 5.7 upgrade. 

Similar to what you are saying I think on the RDS side of things what we should be doing is the following

1. Put MDN in a RO state
2. Create a read replica of the RDS instance
3. Upgrade the read replica of the RDS instance to the new version
4. Point MDN to the read replica with the new version to make sure everything is running ok
5. Upgrade main RDS DB
6. Point MDN back to original RDS DB
7. Take MDN out of maint mode

Does this sound reasonable?

**Comment by jwhitlock** [comment]
Yes, that sounds like it would work
