### ISSUE TITLE
Reduce the number of KumaScript pods

### ISSUE THREAD

**Issue by davidflanagan** [mdn/infra#180]
We currently have 6 nodes dedicated to the KumaScript service. But that services only gets about 1 non-trivial request per minute. And even during usage spikes, the instances are only at about 2% CPU usage (according to our newrelic dashboards)

So I'd like to try using fewer instances. I'd love it if we could get down to 1. But maybe we could try 3 or 2 first.

@jwhitlock thinks there might be a way to experiment with temporary scaling before we make a permanent configuration change, in which case it would be good to handle issue #177 first.

# Acceptance Criteria
* [ ] Resource estimates match KumaScript usage
* [ ] Kumascript pods reduced, 2 pod minimum

**Comment by davidflanagan** [comment]
On the other hand, I'd also be interested in a stress-test on the KumaScript server to see how it handles those spikes when we have only 1 or 2 instances running. There were only 4 instances yesterday, and I didn't notice any difference from the usual 6. The server is I/O bound, and CPU usage remains low during the spikes, so even if we don't land the PR above, we can still probably drop the number of nodes.

**Comment by jwhitlock** [comment]
> We currently have 6 nodes dedicated to the KumaScript service. But that services only gets about 1 non-trivial request per minute. And even during usage spikes, the instances are only at about 2% CPU usage (according to our newrelic dashboards)

@davidflanagan and I went over this info on pods versus nodes in our meeting before I could finish this comment, but it may be helpful for future discussion, so I'm posting it.

We currently deploy 6 kumascript pods. These can be thought of as docker instances spread over the nodes. We tell Kubernetes how much resources we expect each pod to take:

```
    Limits:
      cpu:     4
      memory:  8Gi
    Requests:
      cpu:      500m
      memory:   2Gi
```

This means we telling Kubernetes to expect KumaScript to take up 1/2 a CPU and 2 gigabytes of memory, and spike up to 4 CPUs and 8 gigabytes. These numbers were probably plucked out of the air. Maybe with the metrics server we can revisit and tune them to be more accurate.

A node is an EC2 instance, that has been dedicated as a Kubernetes platform for running instances. We're using 10 [m4.xlarge EC2 instances](https://aws.amazon.com/ec2/instance-types/), with 4 CPUs and 16 gigabytes of memory. The deployments are a lot like when we moved to AWS in October 2017, so a lot of the [Kuma report](https://mozilla.github.io/meao/2017/11/07/kuma-report/#aws-intro) from that month still applies. Each node has roughly 2 web pods and 1 worker pod. Every other node has a kumascript pod. There's 2 API pods for the whole cluster.

Dropping from 6 to 1 kumascript pods will probably not have enough of an impact to remove a node. It is possible that we're already over-resourced, with CDN and other changes we've made. Metrics may help us calculate that. At the same time we (hopefully) have paid for the EC2 instances for 1-3 years in advance, so there are limited windows where we can save money by reducing the number of nodes.

I'd be comfortable with 2 kumascript services, which would allow one to fail (or be on a failing node) without losing the service. I'm not sure if it would be worth losing that redundancy to go to 1 service. This is the staging configuration, however, so you can do some testing there to see the effects.

Smoothing out the hourly spikes is still a good goal, so let's continue with that. Then we could limit the need for a large rendering pool to page moves and bulk rebuilds.

**Comment by escattone** [comment]
The number of kumascript nodes has been reduced from 6 to 4 with the deployment at 2:16pm PT today.

**Comment by limed** [comment]
I spoke to @escattone and we agreed to keep it at 4 for now.
