### ISSUE TITLE
Investigate dns resolution errors

### ISSUE THREAD

**Issue by limed** [mdn/infra#185]
Periodically sentry throws an error complaining about an unknown MySQL host, this appears to be a DNS resolution issue but it only happens periodically. Figure out whats going on here

**Comment by safwanrahman** [comment]
Can we check which DNS server its using?

**Comment by limed** [comment]
This seems somewhat related to: https://github.com/kubernetes/kubernetes/issues/45976

Particularly this statement caught my attention

```
Regarding ndots: You can add a dot to the end of your domain name, this way it will be treated as FQDN and local search will never be attempted arale-ng.cyw3ljy98zq7.eu-west-1.rds.amazonaws.com..

We see the same intermittent DNS resolution issues in all clusters. In our case it's a Python application and we are failing to resolve external domains. It isn't related to kube-dns autoscaling events because we are running a ridiculously high but fixed number of kube-dns pods. We are also not hitting conntrack limits.

Kubernetes 1.9 on AWS, Networking is kubenet, same results with kube-dns:1.14.9 and kube-dns:1.14.5.
```

Which let me down the `ndot` rabbit hole and I found this: https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

I do suspect that this is a `dnsmasq` issue

**Comment by escattone** [comment]
That's a promising find, nice work @limed! It appears that all of our domain names external to the cluster (MySQL, Redis, ElasticSearch, New Relic, etc.) will go through 4 failed, local DNS lookups before making the final good lookup. At the very least, we should try appending a `.` to all of our cluster-external domain names to reduce the traffic on the `kube-dns` service.

**Comment by limed** [comment]
> I think the next step would be to update the stage secrets and try it out. Alternatively, we are on Kubernetes 1.9, so we could try the ndots customization instead (2 or 3 might work), which may help other services.

I did see this actually and did consider this, however ndots customization while available will require you to use this option `--feature-gates=CustomPodDNS=true` to be enabled on the kubelet and api server which in the end I believe will require a rolling upgrade of the cluster

**Comment by jwhitlock** [comment]
OK, let's go with updating stage settings, since that isn't blocked. @limed do you want to do that or have me or @escattone do it?

**Comment by limed** [comment]
> OK, let's go with updating stage settings, since that isn't blocked. @limed do you want to do that or have me or @escattone do it?

I can take this on

**Comment by jwhitlock** [comment]
We haven't seen any negative consequences from using this on staging. We are seeing a significant increase in DNS issues on production. Let's try this fix in production as well.

**Comment by limed** [comment]
I've done a few things to tweak dnsmasq since the resolution errors. Here is some of the things that was take done:

- Edit `kube-dns-autoscaler` configmap to make sure that there are additional dns nodes (We now have 3)
- Set `dnsmasq` option `--dns-forward-max` to 500, this increases the concurrent dns queries allowed

**Comment by limed** [comment]
We have seen a reduction of errors for now I will call this good until it causes significant issues
