### ISSUE TITLE
Pick domain name for kubernetes cluster

### ISSUE THREAD

**Issue by limed** [mdn/infra#19]
Need to pick a few domain names before we can move forward. Here are some suggestions that we discussed in our meeting

- mdn.mozit.cloud
- mozmdn.{cloud,com,net} (This will need to be purchased)
- Something else open to suggestion

My suggestion for the layout of cluster name should be as follows: `k8s.${REGION}.${DOMAIN_NAME}`

**Comment by jwhitlock** [comment]
``mdn.mozit.cloud`` managed by Route53 would be OK with me, if that combo is possible.

**Comment by jwhitlock** [comment]
Some more information from my perspective (hopefully others will tell me when I'm wrong). The "internal DNS" names show up in these cases:

* They are used as the source domains for CloudFront CDN distributions. Some testing procedures require making a similar request to the source domain. 
* SSL certificates often need them as alternate names alongside "official" names.
* The staging instance name (currently developer.allizom.org) shows up in documentation
* Django needs to know the domain name, and by default will refuse connections by IP address or the AWS-allocated "ec2-x-x" name.
* Some day we may resurrect the demo instances project, and this may require scripted creation of one or more subdomains.
*

**Comment by limed** [comment]
Using `mdn.mozit.cloud` if that needs to change or a domain needs to be purchased we can revisit this.
