### ISSUE TITLE
Kubernetes cluster upgrades

### ISSUE THREAD

**Issue by limed** [mdn/infra#192]
We are currently running kubernetes `v1.9.7` there are some issues currently in kubernetes (mainly #185) that would benefit us if we upgraded to the latest version.  The general idea  is to upgrade from v1.9.x -> v1.10.x -> v1.11.x

Pre-upgrade:
1. Make sure `kops` is working and up to date
2. Make sure `kubectl` is working and up to date
3. Review all the terraform changes that `kops` outputs

Upgrade plan:
1. Upgrade the standby cluster first make sure everything is stable
2. Increase the number nodes in the main cluster to accommodate rolling update
3. Upgrade main cluster to v1.10.x and then to v1.11.x
4. Upgrade cluster autoscaler every update needs an image update as documented [here](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases)

**Comment by limed** [comment]
For my future reference as well: https://github.com/kubernetes/kops/blob/master/docs/upgrade.md

**Comment by jwhitlock** [comment]
@limed Is this done, or are there remaining tasks?

**Comment by limed** [comment]
@jwhitlock all done here, closing out
