### ISSUE TITLE
Investigate 504 Gateway Timeouts during editing

### ISSUE THREAD

**Issue by jwhitlock** [mdn/infra#200]
As reported in [bug 1529010](https://bugzilla.mozilla.org/show_bug.cgi?id=1529010), MDN editors are seeing 504 errors from CloudFront during editing:

* Will Bamberg reported 504 on February 14 in a team IRC channel
* Rachel Andrew reported "constant gateway timeout errors today from CloudFront while trying to edit things on MDN." on February 17 in a team Slack channel.
* Sheppy reported "First I got a "publishing error occurred" message, and now I'm getting a 504" in the #mdn IRC channel on February 19, and Chris Mills says he saw them as well.

It appears that editing works after a few attempts.

It is possible that this started before February 14, and went unreported. There have been two deployments in February:

* February 7: https://github.com/mozilla/kuma/compare/ded7edc...00785e4
* February 14: https://github.com/mozilla/kuma/compare/00785e4...f861aa8

The CloudFront logs may show when the 504s increased, to help narrow down when the problem started. It is unknown, but unlikely, that this error would be visible in Sentry.

**Comment by jwhitlock** [comment]
We've made a few changes, as reported on [bug 1529010](https://bugzilla.mozilla.org/show_bug.cgi?id=1529010#c2):

* The Constance config `KUMASCRIPT_TIMEOUT` changed from 300 to 25 seconds. This should result in a "Rendering in progress" message.
* In https://github.com/mdn/infra/pull/202, the origin timeout (how long CloudFront waits) was set to 120 seconds, and the gunicorn timeout (how long gunicorn waits for Kuma) was set to 119 seconds.

These two changes should make 504s less common, or go away entirely.

When KumaScript times out due to a preview, the exception is not caught but instead results in a server error. Ryan has identified the Kuma code that needs an exception handler.

Once the handler is in place, and there are no more reports of 504 timeouts, we can close this bug.

**Comment by escattone** [comment]
https://github.com/mozilla/kuma/pull/5271 has been merged to master and deployed to production.

**Comment by escattone** [comment]
Closing this since [bug 1529010](https://bugzilla.mozilla.org/show_bug.cgi?id=1529010) has been resolved.
