### ISSUE TITLE
Add verification header for ahref.com

### ISSUE THREAD

**Issue by jwhitlock** [mdn/infra#205]
As described in [bug 1531699](https://bugzilla.mozilla.org/show_bug.cgi?id=1531699), the ahref.com tool needs a verification TXT record, ``ahrefs-site-verification_555253e345bfa632b331373380ebc9fc3b4439aaf955dc2d6b2e9566afa73bc2``, to allow scraping MDN at a faster rate. I would be good to have this by April 2019.

**Comment by limed** [comment]
Updated [bug 1531699](https://bugzilla.mozilla.org/show_bug.cgi?id=1531699) but adding my response here. I can only add the TXT record for `_developer.mozilla.org` instead of `developer.mozilla.org` which is generally the way things goes for TXT records, let me know if that works out

**Comment by limed** [comment]
Did more digging, since developer.mozilla.org is a CNAME that points to the CDN we can't create a TXT record for developer.mozilla.org. Hence why the `_` should be used instead

**Comment by limed** [comment]
This has now been verified
