### ISSUE TITLE
Setup papertrail account

### ISSUE THREAD

**Issue by limed** [mdn/infra#21]
Setup a papertrail account.

Tasks:
* [x] Setup a free papertrail account
* [x] Associate with shared email
* [x] Configure logging to account
* [x] Add credit card to account

**Comment by limed** [comment]
An account has been setup under my email, probably need to change it to a shared email and have someone put in their CC information in there

**Comment by limed** [comment]
~$425/month or $5100/year

**Comment by jwhitlock** [comment]
@limed called the right person, papertrail task is DONE
