### ISSUE TITLE
Jenkins jobs sometimes takes longer than expected to finish a job

### ISSUE THREAD

**Issue by limed** [mdn/infra#250]
The build of kuma and kumascript (which basically is just a docker build) sometimes takes longer than 30 minutes. Figure out why this is happening and also figure out if its possible to optimize this step

**Comment by peterbe** [comment]
Does that "build" include running tests?

[Our Travis CI hovers around 17 min](https://travis-ci.org/mozilla/kuma/builds) which is pretty long but somewhat reasonable considering the amount of stuff in kuma.

**Comment by escattone** [comment]
@peterbe No, it often takes a long time (30+ minutes) to just build the Kumascript docker image, specifically it seems to often stall for 25+ minutes on this step: https://github.com/mozilla/kuma/blob/087bf522aed790ee09c9489cda8ad6d2331e0919/docker/images/kumascript/Dockerfile#L33.

**Comment by peterbe** [comment]
It's funny how it takes longer to chown files than it does to download and install them. 
Can we just see if it speeds things up drastically by running the `npm install` with the right user?
