### ISSUE TITLE
kube2iam should be installed on the cluster

### ISSUE THREAD

**Issue by limed** [mdn/infra#28]
Something to look into at a later time but this is something that should be installed on the cluster

https://github.com/jtblin/kube2iam

**Comment by jgmize** [comment]
We use a network policy to block access to the AWS metadata service instead: https://github.com/mozmeao/infra/tree/master/k8s/tools/block-aws

**Comment by limed** [comment]
so EKS now uses IRSA (https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) we should be switching to that instead so this is no longer relevant
