### ISSUE TITLE
Update Terraform to match current AWS configurations after beta launch

### ISSUE THREAD

**Issue by escattone** [mdn/infra#292]
### Description
After the `beta` launch, the Terraform should be update to match the current AWS configurations.

### Acceptance criteria
- [ ] The DNS entries for `beta.developer.mozilla.org` and `beta.developer.allizom.org` have been deleted
- [ ] The terraform in https://github.com/mdn/infra has been updated to reflect the new stage and prod S3 buckets used for serving the document API
- [ ] The terraform in https://github.com/mdn/infra has been updated to reflect the new `mdn-s3-api-prod-uploader` and `mdn-s3-api-stage-uploader` users and their policies
- [x] The terraform in https://github.com/mdn/infra has been updated to reflect the behaviors in the current stage and prod CloudFront distributions (See #291)
- [x] The terraform in https://github.com/mdn/infra has been updated to reflect the new SSL certs, CDN's, etc. for the wiki domain

**Comment by limed** [comment]
Wiki CDN terraform - https://github.com/mdn/infra/pull/330
Behavior changes for primary CDN - https://github.com/mdn/infra/pull/339
