### ISSUE TITLE
Access to K8s

### ISSUE THREAD

**Issue by Gregoor** [mdn/infra#295]
Hi @limed,

I require access to K8s if possible (a readonly DB connection would also work).

Thanks!

**Comment by peterbe** [comment]
How I use it:
```
▶ cat ~/bin/KumaKubectlSessionProd
#!/bin/bash

set -e

export KUBECONFIG=~/.kube/oregon.config  # Was this needed?!

cd /Users/peterbe/dev/MOZILLA/MDN/infra/apps/mdn/mdn-aws/k8s
source regions/oregon/prod.sh  # change to stage.sh for Stage
# Can't use aliases!
name=`kubectl -n mdn-prod get pods | grep 'web-' | head -n 1 | awk '{ print $1 }'`

echo "Going to bash into ${name}"

kubectl -n mdn-prod exec -it "$name" bash
```

**Comment by tobinmori** [comment]
me too! I need access to k8s

**Comment by limed** [comment]
> me too! I need access to k8s

Tobin has access now

**Comment by limed** [comment]
> export KUBECONFIG=~/.kube/oregon.config  # Was this needed?!

Yes this is needed otherwise kubectl won't know which context to use

**Comment by limed** [comment]
> I require access to K8s if possible (a readonly DB connection would also work).

@Gregoor I sent you an email with regards to this so I'm waiting to hear back from you

**Comment by Gregoor** [comment]
@limed I can't seem to find it in my mail account. Do you have a keyword for me?

**Comment by limed** [comment]
Sent info to @Gregoor
