### ISSUE TITLE
Switch to m5 class of EC2 instances

### ISSUE THREAD

**Issue by limed** [mdn/infra#296]
We're currently using an m4 class of instances which is the previous generation of the general purpose instances. As it stands all of our k8s nodes use the m4 class, so we should take some time to actually upgrade them to the newest class.

Once of the benefits of upgrading is that it will be cheaper to run and also provides us with more flexibility when buying RIs from AWS

**Comment by limed** [comment]
Instances currently need updating

us-west-2
- k8s ec2 master - m4.large
- k8s ec2 nodes - m4.xlarge

eu-west-1
- k8s ec2 master - m4.large
- k8s ec2 nodes - m4.xlarge

**Comment by escattone** [comment]
@limed and I decided to do this on Wednesday Oct. 2, 2019 from 5pm-8pm Pacific time. I'm going to take MDN into/out-of maintenance mode (read-only mode) and be available just in case something goes wrong. I've already announced the read-only period via Soapbox on MDN stage and prod.
