### ISSUE TITLE
Switch to db.m5 class of RDS instances

### ISSUE THREAD

**Issue by limed** [mdn/infra#297]
The m5  class is currently the latest generation so we should take some time to upgrade the RDS db to this new instance class. This task should be possible without downtime but we should probably put MDN under readonly mode before doing this, which means we need a downtime window to do this.

**Comment by tobinmori** [comment]
@atopal when is a good time for a temporary outage? MDN will have to be down for a while for this to happen.

**Comment by limed** [comment]
> Just to be clear, we are putting MDN in to read only mode, it will still be available to users to read articles, right? Assuming that's true, can you provide a time window?

Correct MDN will be in a readonly state during this time, for a time window I will say give myself a 2 or 3 hour window during this time to actual do the conversion. The bulk of the work unfortunately will involve  changing the instance type.

> In general 5pm pacific is when we have the least amount of users during the week. An ideal time is later afternoon on a Sunday, that's when we have the least amount of traffic overall.

I can work with a Sunday 5PM pacific, does any of the Sundays work or do you have a preference of which week week?

**Comment by escattone** [comment]
@limed and I decided to do this on Wednesday Oct. 2, 2019 from 5pm-8pm Pacific time. I'm going to take MDN into/out-of maintenance mode (read-only mode) and be available just in case something goes wrong. I've already announced the read-only period via Soapbox on MDN stage and prod.

**Comment by tobinmori** [comment]
Great!Thanks @limed and @escattone!

@limed I'm assuming any Sunday is fine.
