### ISSUE TITLE
Serve Kuma attachments from S3 in production

### ISSUE THREAD

**Issue by callahad** [mdn/infra#354]
Fixes mdn/kuma#5798

Now that mdn/kuma#5882 and mdn/kuma#5998 have landed, it's time to get this turned on in prod!

__Note:__ S3 Buckets and Cloudfront CDN were configured in #336 / #346.

Here's the checklist, to the best of my knowledge:

1. **Configure Kuma's access to S3**
    **Note:** This just *configures* S3, it doesn't *enable* it.
    - [x] Set the following environment variables:
        - [x] `ATTACHMENTS_AWS_ACCESS_KEY_ID`
        - [x] `ATTACHMENTS_AWS_SECRET_ACCESS_KEY`
        - [x] `ATTACHMENTS_AWS_STORAGE_BUCKET_NAME` (e.g., `mdn-media-prod`)
        - [x] `ATTACHMENTS_AWS_S3_REGION_NAME` (e.g., `us-west-2`)
        - [x] `ATTACHMENTS_AWS_S3_CUSTOM_DOMAIN` (e.g., `media.prod.mdn.mozit.cloud`)
    - [ ] ~~If necessary, override `ATTACHMENTS_AWS_S3_ENDPOINT_URL`, which defaults to `https://{BUCKET_NAME}.s3.amazonaws.com`
      (for example, you might want `https://mdn-media-prod.s3.us-west-2.amazonaws.com` instead)~~ We no longer want to do this, since it breaks `vhost` S3-bucket addressing.
    - [x] Redeploy Kuma, ensuring it is running [this commit](https://github.com/mdn/kuma/commit/a703414b6a9f2c2181d8ada308216382a802a928) or later
2. **Disable File Uploads**
    - [x] Notify MDN content team that attachment uploads will be disabled
    - [x] Set the Constance flag `WIKI_ATTACHMENTS_DISABLE_UPLOAD` to `True`
    - [x] Verify by opening the editor for a wiki document. Ensure there is no "Upload Files" button under the "Attachments" header at the bottom of the page.
3. **Sync the attachments**
    - [x] Copy all attachments data from EFS to S3
        - [x] Apply the following `CacheControl` policy for each item: `public, max-age=31536000, immutable`
    - [x] Pick a random attachment, for example the [DevEdition logo](https://mdn.mozillademos.org/files/15588/logo-developer-quantum.png) at the bottom of the [Tools](https://developer.mozilla.org/en-US/docs/Tools) page. Note its:
        - [x] Kuma URL: `https://mdn.mozillademos.org/files/15588/logo-developer-quantum.png`
        - [x] File Path (via the [Django Admin](https://developer.mozilla.org/admin/attachments/attachment/15588/change/)): `attachments/2017/10/19/15588/c0326751d308fcda882795f44d679388/logo-developer-quantum.png`
    - [x] Verify that the same attachment is available by appending its File Path to:
        - [x] Our S3 bucket URL
        - [x] Our Cloudfront endpoint URL
    - [x] Verify that the attachment is served with the correct `CacheControl` header ("immutable") when accessed via:
        - [x] Our S3 bucket URL
        - [x] Our Cloudfront endpoint URL
4. **Tell Kuma to use S3 instead of EFS**
    - [x] Set the `ATTACHMENTS_USE_S3` environment variable to `True`
    - [x] Redeploy Kuma to enable S3
    - [x] Verify that the attachment's Kuma URL from the previous step now redirects to Cloudfront
        (The old data may still be in CloudFront's cache for up to 15 minutes... maybe use the Admin to find a really old image that's definitely not cached anywhere and make sure _that_ redirects?)
    - [x] Verify that attachments display correctly on a few random pages
    - [x] Use the Django Admin to create a new Attachment or AttachmentRevision
      This should work despite uploads being disabled on the Wiki
    - [x] Verify that the new attachment is accessible via:
        - [x] Its Kuma URL, which should redirect to CloudFront
        - [x] Its direct S3 bucket URL
        - [x] Its CloudFront URL
5. **Re-Enable File Uploads**
    - [x] Set the Constance flag `WIKI_ATTACHMENTS_DISABLE_UPLOAD` to `False`
    - [x] Verify by opening the editor for a wiki document. Ensure there "Upload Files" button appears under the "Attachments" header at the bottom of the page.
    - [x] Verify by uploading an attachment somewhere on the Wiki
    - [x] Notify MDN content team that attachment uploads are enabled again

---

**If anything goes horribly wrong:**
- [ ] Set the `ATTACHMENTS_USE_S3` environment variable to `False`
- [ ] Redeploy Kuma to disable S3 and return to EFS

**Comment by callahad** [comment]
@limed and @escattone... this one's for you :)

**Comment by peterbe** [comment]
@limed It's not really urgent but Dan is handing this over because he's going on PTO so he's hoping that Ryan and/or myself can be there with you to do this stuff. Also, I'd love to not let this slip into the new year as we might lose Dan to go back to devrel tasks. 

Would you mind reading it through and see if stuff makes sense?
Would you mind taking the time to schedule a meeting that Ryan and I can attend?

Also, very important, we should do the WHOLE thing for developer.allizom.org first. There it's even easier too because anybody can just jump into any old page and click to edit and add an image of a cat.

**Comment by escattone** [comment]
@callahad Just looked through this in detail, and it looks fantastic, nice work! Thank you for your careful and thorough attention to detail!

**Comment by escattone** [comment]
@peterbe Myself and @limed met yesterday and we were thinking of doing this next week, starting with stage and either doing prod afterwards on the same day or a later day.

**Comment by peterbe** [comment]
> we were thinking of doing this next week, starting with stage and either doing prod afterwards on the same day or a later day.

Don't let my timezone be a blocker for progress but if you could make it your early, I can be around on standby. If nothing else, it's good to have another set of ears to bounce ideas with if things go wrong or if you need help with communications.

**Comment by callahad** [comment]
The commit message for #358 inadvertantly closed this issue. Reopening.

**Comment by escattone** [comment]
Done on stage and prod!!!!!!!!!! Works like a charm! Thanks so much to everyone involved!

**Comment by escattone** [comment]
For the record, wanted to associate https://github.com/mdn/kuma/pull/6257 with this issue (couldn't do it through ZenHub).

**Comment by escattone** [comment]
Since everything seems to be working well so far, I'm going to close this issue as done. We can open further issues if we need to fix anything.
