### ISSUE TITLE
Deploy the MDN Insights website to PROD

### ISSUE THREAD

**Issue by tobinmori** [mdn/infra#356]
**What:** 

Currently hosted at: 
https://insights.developer.allizom.org/

We need to switch this to Production-grade, update the DNS and serve it from the CDN via:
https://insights.developer.mozilla.org/

My understanding is that this is a static site so there should be no build steps required. 

**When:**

A final push after end of day Dec. 16. (Pacific Time) - when the final content changes should be updated. (currently this site has placeholder text). Ideally, this is live Dec. 18ish.

**Comment by limed** [comment]
This site is now live
