### ISSUE TITLE
Developer access to MDN RDS replica (or backup instance)

### ISSUE THREAD

**Issue by tobinmori** [mdn/infra#372]
The MDN Dev team will need in the coming weeks access to an RDS replica or recent backup. Eventually a straight replica.

Purpose: the team will need to import RDS data to sync with Github, and download MDN docs.

Timeline: end of Feb or earlier would be great.  

Possible option: SSH tunneling, but open to others!

**Comment by peterbe** [comment]
> This should be done

How do I access it? 

Perhaps we can reopen this issue until we have that documented. What do you think?

**Comment by escattone** [comment]
This was done, and no longer needed.
