### ISSUE TITLE
I can't sign in to kubernetes on Stage

### ISSUE THREAD

**Issue by peterbe** [mdn/infra#374]
I've been using this technique to successfully sign in to PROD. 
So I cloned my script and changed from `regions/oregon/prod.sh` to `regions/oregon/stage.sh`

```
▶ cat `which KumaKubectlSessionStage`
#!/bin/bash

set -e

export KUBECONFIG=~/.kube/oregon.config  # Was this needed?!

cd /Users/peterbe/dev/MOZILLA/MDN/infra/apps/mdn/mdn-aws/k8s
source regions/oregon/stage.sh  # change to prod.sh for Prod
# Can't use aliases!
name=`kubectl -n mdn-prod get pods | grep 'web-' | head -n 1 | awk '{ print $1 }'`

echo "Going to bash into ${name} ON STAGE"

kubectl -n mdn-prod exec -it "$name" bash
```

But when I do this, I end up inside the PROD instance. 

The problem is that `source regions/oregon/stage.sh` doesn't seem to do what you expect.

**Comment by peterbe** [comment]
@limed Please when time allows. This is actively blocking me from debugging a P1 bug that's happening on stage.

**Comment by peterbe** [comment]
By the way, here's how I confirm that I end up on PROD:

```
▶ KumaKubectlSessionStage
--> Setting environment to STAGE in OREGON
Going to bash into web-69789f5cd9-496b6 ON STAGE
kuma@web-69789f5cd9-496b6:/app$ ./manage.py shell_plus
...
>>> settings.DOMAIN
'developer.mozilla.org'
```

(you can also check other things such as the number of documents which is clearly a lot more on prod)

**Comment by escattone** [comment]
@peterbe This is a problem with your script. In your script, you're using `-n mdn-prod` within these two lines:

> name=`kubectl -n mdn-prod get pods | grep 'web-' | head -n 1 | awk '{ print $1 }'`
> ...
> kubectl -n mdn-prod exec -it "$name" bash

when you should be using `-n mdn-stage` instead.

**Comment by peterbe** [comment]
Oh my! Not only did I miss that, I also had to change the last line too. Now, this works:

```
▶ cat bin/KumaKubectlSessionStage
#!/bin/bash

set -e

export KUBECONFIG=~/.kube/oregon.config  # Was this needed?!

cd /Users/peterbe/dev/MOZILLA/MDN/infra/apps/mdn/mdn-aws/k8s
source regions/oregon/stage.sh  # change to prod.sh for Prod
# Can't use aliases!
name=`kubectl -n mdn-stage get pods | grep 'web-' | head -n 1 | awk '{ print $1 }'`

echo "Going to bash into ${name} ON STAGE"

kubectl -n mdn-stage exec -it "$name" bash
```
