### ISSUE TITLE
Setup an elastic.co account

### ISSUE THREAD

**Issue by limed** [mdn/infra#38]
This is a hosted elastic search service thats needed. Setup an an account [here](https://www.elastic.co/) and get a corp card placed in on that account. Budget is around $320/month $271/month with an annual contract.

**Comment by escattone** [comment]
@limed I think currently we paying around $145/month for the production instance and about $15/month for the stage instance, so I would say the monthly cost would not be more than $200/month.

**Comment by limed** [comment]
> @limed I think currently, for MDN only, we're paying around $145/month for the production instance and about $15/month for the stage instance, so I would say the monthly cost would not be more than $200/month.

Thanks @escattone, I'll get his information to our vendor folks

**Comment by limed** [comment]
Account has been setup
