### ISSUE TITLE
Send a changelog on MDN deploy to prod/stage. 

### ISSUE THREAD

**Issue by tobinmori** [mdn/infra#383]
Upon MDN Deploy to stage an email with a changelog should be sent to 'mdn-dev@mozilla.com'

Changelog ideally contains new commits included in deploy, if that's too hard a link to the github diff summary.

**Comment by peterbe** [comment]
Can the email please contain the link https://whatsdeployed.io/s/HC0/mdn/kuma
That way, if you click that link before Prod gets upgraded you get a nice list of what glorious commits just went into Stage that haven't made it to Prod yet. 
Also, Whatsdeployed will have those GitHub compare URLs that you might need to make a full diff of what the commits mean in terms of the source code.

**Comment by escattone** [comment]
Closing, since I don't think this makes sense any longer since the launch of Yari.
