### ISSUE TITLE
Re-rendering after save takes longer than usual

### ISSUE THREAD

**Issue by Elchi3** [mdn/infra#421]
**Summary**
Since yesterday or so, for me, page re-rendering is quite slow after saving an edit. The "An update to this document has been scheduled." message is showing unusually long.

**Steps To Reproduce (STR)**

1. Edit an MDN page
2. Save

**Actual behavior**
"An update to this document has been scheduled." is shown longer, document isn't re-rendered reasonably fast.

**Expected behavior**
Document re-renders without much waiting.

**Additional context**
If this is on purpose, then okay. Just wanted to let you know this feedback.

**Comment by escattone** [comment]
Thanks for letting us know @Elchi3! I'm going to increase the size of the `api` deployment by 3x and add another pod to the size of the `kumascript` deployment. That's the combination that I find works well when rendering lots of documents and I think it should be permanent.

**Comment by Elchi3** [comment]
This is happening again today for me.

**Comment by Elchi3** [comment]
Actually, it worse than just long re-rendering for me. I don't see new changes rendered at all.
https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#HTML should have @chrisdavidmills' edit about link preload (https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features$compare?locale=en-US&to=1627107&from=1626940) but I don't have that rendered for me.

**Comment by tobinmori** [comment]
thanks @Elchi3, 

@escattone and @limed - did you see our rds looks like it's being overwhelmed? any idea what might be causing this? i can take a look at our rds instance. . .

**Comment by escattone** [comment]
@Elchi3 As @tobinmori mentioned, I think this was related to our RDS instance being overwhelmed with too many connections, which was a result of testing our new EKS cluster while it was running on the same RDS instance that we use with our current production cluster. @limed has resolved this, and I checked the pages you mentioned above and they seem good to me now, so hopefully this is no longer an issue?

**Comment by Elchi3** [comment]
Works as expected for me today. Thanks!
