### ISSUE TITLE
Consider dropping the distinction between api and web pods

### ISSUE THREAD

**Issue by escattone** [mdn/infra#424]
We currently distinguish between two kinds of Django pods, `api` and `web`, where the `api` pods are not public-facing and are dedicated to serving the `kumascript` pods, i.e. dedicated to the task of rendering macros. I think this distinction should be removed, and the `web` pods should serve both the public requests as well as the `kumascript` requests. This would not only simplify the architecture, but more efficiently use the pool of Django instances.

NOTE: This would require a change on the `kumascript` side, changing references from `http://web/` to `http://api`.

**Comment by peterbe** [comment]
It's how we're [testing kuma in `docker-compose`](https://github.com/mdn/kuma/commit/ffed887423e72754d3f27021131cdc1f8d1f35ad#diff-4e5e90c6228fd48698d074241c2ba760) in local development.

**Comment by limed** [comment]
I don't think we should do this this goes against the whole microservices architecture that kubernetes / containerization gives us. We should keep `api` and `web` separate just my 2c

**Comment by escattone** [comment]
Obsolete with the launch of Yari (`api` pods will go away soon as we dismantle much of Kuma after the launch of Yari).
