### ISSUE TITLE
Set up a Disaster Recovery (DR) cluster and AWS resources

### ISSUE THREAD

**Issue by jwhitlock** [mdn/infra#51]
A Disaster Recovery (DR) cluster is a standby cluster that can rapidly be promoted if there is a region-level failure in AWS.

# Acceptance Criteria
- [ ] A disaster recovery cluster is configured
- [ ] A read-only replica of the new production database is configured
- [ ] The ``standby-push`` branch updates the cluster applications

**Comment by limed** [comment]
A cluster has been created in Frankfurt (eu-central-1) together with all the AWS resources it needs.

- memcache
- efs
- redis
- RDS prod replica

**Comment by escattone** [comment]
@limed I was just looking around and noticed it was all there, thanks! As part of the my work for the next sprint, I'll take it from here!

**Comment by limed** [comment]
Done on my end
