### ISSUE TITLE
Plan monitoring without Datadog

### ISSUE THREAD

**Issue by jwhitlock** [mdn/infra#52]
Plan on operational monitoring without Datadog, and see if Amazon Cloudwatch is a sufficient replacement.

Current Datadog usage:
* Repeats of AWS service monitoring, such as counts of ELB and CDN requests
* Kubernetes-level stats, such as bytes transmitted and pod memory usage
* The depth of Celery queues in Redis, 1 minute resolution.

# Acceptance Criteria
* [ ] The tech team has a plan for monitoring in the future, which may or may not include Datadog
* [ ] Follow-on tasks are written and scheduled

**Comment by limed** [comment]
We have decided to use influxdb and have removed datadog
